/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package learn;

/**
 *
 * @author roshn
 */
public class BodyMassIndex extends javax.swing.JFrame {

    /**
     * Creates new form BodyMassIndex
     */
    public BodyMassIndex() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        GewichtLabel = new javax.swing.JLabel();
        LengteLabel = new javax.swing.JLabel();
        LeeftijdLabel = new javax.swing.JLabel();
        VulLengte = new javax.swing.JTextField();
        VulLeeftijd = new javax.swing.JTextField();
        ConvertBMI = new javax.swing.JButton();
        VulGewicht = new javax.swing.JTextField();
        AdviesButton = new javax.swing.JButton();
        BMIR1 = new javax.swing.JLabel();
        BMIR2 = new javax.swing.JLabel();
        BMIR3 = new javax.swing.JLabel();
        AdviesR1 = new javax.swing.JLabel();
        BMILabel = new javax.swing.JLabel();
        MeerButton = new javax.swing.JButton();
        BMIRekenmachine = new javax.swing.JLabel();
        AdviesR2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Bereken je BMI");
        setBackground(new java.awt.Color(51, 255, 204));
        setForeground(new java.awt.Color(240, 240, 240));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        GewichtLabel.setFont(new java.awt.Font("Cambria", 1, 36)); // NOI18N
        GewichtLabel.setText("Gewicht in kilogram");
        getContentPane().add(GewichtLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(683, 166, -1, -1));

        LengteLabel.setFont(new java.awt.Font("Cambria", 1, 36)); // NOI18N
        LengteLabel.setText("Lengte in meters");
        getContentPane().add(LengteLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(683, 246, -1, -1));

        LeeftijdLabel.setFont(new java.awt.Font("Cambria", 1, 36)); // NOI18N
        LeeftijdLabel.setText("Leeftijd");
        getContentPane().add(LeeftijdLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(683, 331, -1, -1));

        VulLengte.setFont(new java.awt.Font("Cambria", 1, 36)); // NOI18N
        getContentPane().add(VulLengte, new org.netbeans.lib.awtextra.AbsoluteConstraints(213, 243, 327, -1));

        VulLeeftijd.setFont(new java.awt.Font("Cambria", 1, 36)); // NOI18N
        getContentPane().add(VulLeeftijd, new org.netbeans.lib.awtextra.AbsoluteConstraints(213, 328, 327, -1));

        ConvertBMI.setFont(new java.awt.Font("Cambria", 1, 36)); // NOI18N
        ConvertBMI.setText("Bereken je BMI!");
        ConvertBMI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConvertBMIActionPerformed(evt);
            }
        });
        getContentPane().add(ConvertBMI, new org.netbeans.lib.awtextra.AbsoluteConstraints(407, 475, -1, -1));

        VulGewicht.setFont(new java.awt.Font("Cambria", 1, 36)); // NOI18N
        VulGewicht.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VulGewichtActionPerformed(evt);
            }
        });
        getContentPane().add(VulGewicht, new org.netbeans.lib.awtextra.AbsoluteConstraints(213, 163, 327, -1));

        AdviesButton.setFont(new java.awt.Font("Cambria", 1, 36)); // NOI18N
        AdviesButton.setText("Advies?");
        AdviesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AdviesButtonActionPerformed(evt);
            }
        });
        getContentPane().add(AdviesButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 760, 210, 60));

        BMIR1.setFont(new java.awt.Font("Cambria", 1, 36)); // NOI18N
        BMIR1.setText("BMI1");
        getContentPane().add(BMIR1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 570, 1130, 50));

        BMIR2.setFont(new java.awt.Font("Cambria", 1, 36)); // NOI18N
        BMIR2.setText("BMI2");
        getContentPane().add(BMIR2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 630, 1130, 50));

        BMIR3.setFont(new java.awt.Font("Cambria", 1, 36)); // NOI18N
        BMIR3.setText("BMI3");
        getContentPane().add(BMIR3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 690, 1150, 50));

        AdviesR1.setFont(new java.awt.Font("Cambria", 1, 36)); // NOI18N
        AdviesR1.setText("Advies1");
        getContentPane().add(AdviesR1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 850, 1082, -1));

        BMILabel.setFont(new java.awt.Font("Cambria", 1, 36)); // NOI18N
        BMILabel.setText("BMI Label");
        getContentPane().add(BMILabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(213, 398, 327, -1));

        MeerButton.setFont(new java.awt.Font("Cambria", 1, 36)); // NOI18N
        MeerButton.setText("Help, ik wil afvallen/aankomen!");
        MeerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MeerButtonActionPerformed(evt);
            }
        });
        getContentPane().add(MeerButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 760, 570, 60));

        BMIRekenmachine.setFont(new java.awt.Font("Cambria", 1, 48)); // NOI18N
        BMIRekenmachine.setText("BMI Rekenmachine");
        getContentPane().add(BMIRekenmachine, new org.netbeans.lib.awtextra.AbsoluteConstraints(342, 51, -1, -1));

        AdviesR2.setFont(new java.awt.Font("Cambria", 1, 36)); // NOI18N
        AdviesR2.setText("Advies2");
        getContentPane().add(AdviesR2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 920, 1082, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Sianie\\Pictures\\weegschaal.jpg")); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-2, 0, 1210, 1010));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void VulGewichtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VulGewichtActionPerformed
        //  TODO add your handling code here:
    }//GEN-LAST:event_VulGewichtActionPerformed

    private void ConvertBMIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConvertBMIActionPerformed
        // TODO add your handling code here:
        float Gewicht  = (int) (Float.parseFloat(VulGewicht.getText())); 
        float Lengte = (Float.parseFloat(VulLengte.getText())); 
        int Leeftijd = (Integer.parseInt(VulLeeftijd.getText()));
        float BMI   = ((Gewicht / (Lengte * Lengte)));
        double RoundOff = (double) Math.round(BMI * 100) / 100;

        
        BMILabel.setText("Je BMI is " + RoundOff);
        if (RoundOff <= 18.5)
        {
            BMIR1.setText("Ondergewicht. U gezondheidsrisico: ");
            BMIR2.setText("te licht, te weinig reserve bij ziekte.");
        }
        else if (RoundOff > 18.5 && RoundOff <= 24.9)
        {
            BMIR1.setText("Gezond of normaal gewicht.");
            BMIR2.setText("U zit goed, probeer in evenwicht te blijven. ");
        }
        else if (RoundOff > 25 && RoundOff <= 29.9)
        {
            BMIR1.setText("Overgewicht.");
            BMIR2.setText("U kunt het liefst afslanken tot gezond gewicht. ");
        }
            else if (RoundOff > 30 && RoundOff <= 39.9)
        {
            BMIR1.setText("Obesitas (ernsitg overgewicht)."); 
            BMIR2.setText("U heeft een zeer grote kans op het ontstaan van diabetes mellitus, "); 
            BMIR3.setText( "hart- en vaataandoeningen, onvruchtbaarheid en gewrichtsklachten.");
        }
            else
        {
            BMIR1.setText("Morbide obesitas (ziekelijk overgewicht.");
            BMIR2.setText("U moet dringend afvallen, want uw gezondheid is in groot gevaar!");
        }
        
    }//GEN-LAST:event_ConvertBMIActionPerformed

    private void AdviesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AdviesButtonActionPerformed
        // TODO add your handling code here:
        float Gewicht      = (int) (Float.parseFloat(VulGewicht.getText())); 
        float Lengte       = (Float.parseFloat(VulLengte.getText())); 
        float BMI          = ((Gewicht / (Lengte * Lengte)));
        double RoundOff    = (double) Math.round(BMI * 100) / 100;
        double MinGewicht   = (18.5 * Lengte * Lengte) ;
        double MaxGewicht   = (24.9 * Lengte * Lengte) ;
        double AfvalGewicht =  (Gewicht - MaxGewicht);   
        double AankomGewicht = (MinGewicht - Gewicht);
        double Afvallen = (double) Math.round(AfvalGewicht * 100)/100 ;
        double Aankomen = (double) Math.round(AankomGewicht *100)/100 ;
        
                if (RoundOff < 18.5)
                    AdviesR1.setText("U moet " + Aankomen + " kg moet aankomen om weer gezond te zijn.") ;
                if (RoundOff > 18.5 && RoundOff <= 24.9)
                    AdviesR1.setText("Je gewicht past goed bij je lengte.");
                if (RoundOff > 25)
                    AdviesR1.setText("U moet " + Afvallen + " kg moet afvallen om weer gezond te zijn.");
                    
                    
                
                
                
              
        
        
                
         

        
        
    }//GEN-LAST:event_AdviesButtonActionPerformed

    private void MeerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MeerButtonActionPerformed
        // TODO add your handling code here:
        float Gewicht      = (int) (Float.parseFloat(VulGewicht.getText())); 
        float Lengte       = (Float.parseFloat(VulLengte.getText()));
        double Leeftijd = (Integer.parseInt(VulLeeftijd.getText()));
        float BMI          = ((Gewicht / (Lengte * Lengte)));
        double RoundOff    = (double) Math.round(BMI * 100) / 100;
        
        Vetpercentage OpenFrame = new Vetpercentage();
        OpenFrame.details(RoundOff, Leeftijd);
        this.dispose();
        OpenFrame.setVisible(true);
        
    }//GEN-LAST:event_MeerButtonActionPerformed
   
        
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BodyMassIndex.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BodyMassIndex.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BodyMassIndex.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BodyMassIndex.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BodyMassIndex().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AdviesButton;
    private javax.swing.JLabel AdviesR1;
    private javax.swing.JLabel AdviesR2;
    private javax.swing.JLabel BMILabel;
    private javax.swing.JLabel BMIR1;
    private javax.swing.JLabel BMIR2;
    private javax.swing.JLabel BMIR3;
    private javax.swing.JLabel BMIRekenmachine;
    private javax.swing.JButton ConvertBMI;
    private javax.swing.JLabel GewichtLabel;
    private javax.swing.JLabel LeeftijdLabel;
    private javax.swing.JLabel LengteLabel;
    public static javax.swing.JButton MeerButton;
    public static javax.swing.JTextField VulGewicht;
    public static javax.swing.JTextField VulLeeftijd;
    public static javax.swing.JTextField VulLengte;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
